### ISSUE TITLE
Bug: Renaming a folder causes access is denied error

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#379]
I can create new folders, but upon rename it fails with access denied error? 

(ALSO: Unable to delete the folder). But it will let me add as many folders or sub-folders as I want.

(EDIT: However, I can rename a folder, if it contains a component, if it is empty, or contains other folders only, I can not rename)

I even tried right-clicking gum.exe and opening as administrator and still go the the error

System.IO.IOException: 'Access to the path 'C:\Users\jerem\OneDrive\Documents\GUM\Test2\Components\mine\annoder\' is denied.'

https://github.com/user-attachments/assets/75f19687-e6d5-479d-be6d-7afe67fcf91a

![image](https://github.com/user-attachments/assets/2c1d8650-dbf7-4ae1-9a16-b1b0d90d0523)

![image](https://github.com/user-attachments/assets/e80d0537-c666-4325-9456-74d4edc17f5d)

![image](https://github.com/user-attachments/assets/d55c288b-4842-43ea-95fd-2a2e6e9e5de0)

ee the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.IOException: Access to the path 'C:\Users\jerem\OneDrive\Documents\GUM\Test2\Components\mine\annoder\' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at System.IO.Directory.Delete(String path)
   at Gum.Managers.ElementTreeViewManager.HandleRenameFolder(Object sender, EventArgs e) in C:\git\Gum\Gum\Plugins\InternalPlugins\TreeView\ElementTreeViewManager.RightClick.cs:line 590
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolSt

**Comment by vchelaru** [comment]
I could not reproduce this error; however, I did find a different bug related to renaming. If an empty folder was renamed, it would just be deleted instead of renamed. I fixed this problem. I also refactored the code a little bit and added a try/catch around the code that I think is failing in your case. Please try again and see if you can get it to repro after this change. 

If you can get it to repro, you may get a more user-friendly error about an empty folder not being deleted. If you think think this is good enough, let me know.

8f13361be9cc70763885659c150b0ae9a497957d
